- name: Instalar Dependencias, clone repo e start API
  hosts: aws-api
  become: true

  vars:
    github_repo: "https://github.com/brunogenerali/Challenge_DevOps-2.git"
    app_dir: "/home/ubuntu/api"
    
  tasks:
    - name: Instalar pacotes Java 17, e Maven
      apt:
          name:
            - openjdk-17-jre-headless
            - openjdk-17-jdk-headless
            - maven
            - python3        
            - python3-pip
          update_cache: yes
          state: present
    
    - name: Clonar Repositorio da API
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_dir }}"
    